### ISSUE TITLE
RemoteDeploymentSample Exception on Deployer shutdown

### ISSUE THREAD

**Issue by shilonosov** [petabridge/akkadotnet-code-samples#29]
Hi @skotzko,

Here is an issue for sample.

I've tried the RemoteDeploymentSample solution and noted that in case of "normal" (hit any key) termination of Deployer following exception appear:

[ERROR][16/07/2015 18:02:47][Thread 0021][[akka://DeployTarget/system/transports
/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3a%2f%2fDeployTarget%40127.0.0.1%3a6
202-1]] Underlying transport closed.
Cause: Helios.Exceptions.HeliosConnectionException: An existing connection was f
orcibly closed by the remote host ---> System.Net.Sockets.SocketException: An ex
isting connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at Helios.Reactor.Tcp.TcpProxyReactor.ReceiveCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
[ERROR][16/07/2015 18:02:47][Thread 0010][[akka://DeployTarget/system/endpointMa
nager/reliableEndpointWriter-akka.tcp%3a%2f%2fDeployer%40localhost%3a6201-1/endp
ointWriter]] AssociationError [akka.tcp://DeployTarget@localhost:8090] <- akka.t
cp://Deployer@localhost:6201: Error [Shut down address: akka.tcp://Deployer@loca
lhost:6201] [   at Akka.Remote.EndpointReader.HandleDisassociated(DisassociateIn
fo info)
   at Akka.Remote.EndpointReader.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
Cause: Unknown
[ERROR][16/07/2015 18:02:47][Thread 0010][akka://DeployTarget/system/endpointMan
ager/reliableEndpointWriter-akka.tcp%3a%2f%2fDeployer%40localhost%3a6201-1] Shut
 down address: akka.tcp://Deployer@localhost:6201
Cause: Akka.Remote.ShutDownAssociation: Shut down address: akka.tcp://Deployer@l
ocalhost:6201 ---> Akka.Remote.Transport.InvalidAssociationException: The remote
 system terminated the association because it is shutting down.
   --- End of inner exception stack trace ---
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SystemInvoke(Envelope envelope)

How to make it not to throw an exception on Deployer termination?

**Comment by skotzko** [comment]
@shilonosov this is intended behavior, as Akka.Remote logs an error when the association it has with a remote system closes. 

The error message will happen regardless--that is Akka.Remote doing its job--but you should also have seen, right after the error message, a statement that said `Was address terminated? True`.

The reason we see this message right after (the `Was address terminated?` message) is because we've `DeathWatch`ed the remote actor ([see line 21](https://github.com/petabridge/akkadotnet-code-samples/blob/master/RemoteDeploy%2FRemoteDeploy.Deployer%2FProgram.cs#L21)).

With this `Context.Watch()` we are demonstrating a way to listen to see if the reason we received a `Terminated` message was because the `Association` between the two systems closed. The `Terminated.AddressTerminated` property returns true if the reason why we're receiving
this death watch notification is because the association between our current `ActorSystem`
and the remote `ActorSystem` that `Terminated.ActorRef` lived on failed.

Does that make sense?
