### ISSUE TITLE
Definition of "resilient"?

### ISSUE THREAD

**Issue by softwaretirol** [petabridge/akkadotnet-code-samples#61]
Hello,

for my understanding, with Akka.net it should be possible to create systems which are resilient and self-healing. With the WebCrawler example everything is working like expecting, but if the CrawlerService is crashing and afterwards restarted nothing works anymore?

Do I have any configuration issue here or do I misunderstand the situation?

**Comment by Aaronontheweb** [comment]
@softwaretirol sorry for not responding sooner, but basically there's a lifecycle that cluster nodes go through which we explain here: http://getakka.net/articles/clustering/cluster-overview.html#how-a-cluster-forms

Once a cluster has formed, the nodes are permanent members of the cluster unless they issue a `Leave` command or if they are forcefully removed via a `Down` command, the latter of which occurs when nodes become unreachable. Reachability is an orthogonal concept to node membership; a node being temporarily disconnected from the cluster doesn't affect its membership, only its reachability. If a node is "unreachable" that's consider to be a temporary network issue and the cluster will, by default, wait until that reachable node rejoins the network.

This is where most users get confused: they expect that unreachability == node leaving the cluster. This is wrong and frankly a brittle network design. If you have state on either side of a network partition, you want to give those nodes a chance to reconnect and re-establish communication after the network partition has cleared. 

The issue you're running into on WebCrawler is that we launch everything on port 0 there, so restarting a node looks like one old node going unreachable and a new node attempting to join because the addresses are different. Using a static port number in this scenario would allow the old node to re-join the cluster seamlessly after a reboot. New nodes aren't allowed to join the cluster when at least one current member is unreachable, so we also have to down the unreachable node in the cluster. This can be done automatically with the new features we're adding in 1.3.3 http://getakka.net/articles/clustering/split-brain-resolver.html or manually like a tool with Petabridge.Cmd: https://cmd.petabridge.com/

There's more detail to go into here, but I hope you've found this helpful.
